server:
  port: 9001

spring:
  application:
    name: PLAYER-SERVICE
  config:
    import: "optional:configserver:http://localhost:9296"
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:player-service
    driver-class-name: org.h2.Driver
    username: "adel"
    password: "pass"

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      join_team:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED