server:
  port: 9004

spring:
  application:
    name: CONTRACT-SERVICE
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:contract-service
    driver-class-name: org.h2.Driver
    username:
    password: