server:
  port: 9003

spring:
  application:
    name: TEAM-SERVICE
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:team-service
    driver-class-name: org.h2.Driver
    username: "adel"
    password: "pass"